- serverless.yml
Using Lambda stages we can provide both a 'dev' and 'prod' dashboard experience.
> Stage the Dashboard

- serverless.yml
This is a little bit cheaper, plus it is where everything else is
anyway, I also added our CNAME for the dev-dashboard.
> Move our region to us-west-2

- .travis.yml
- package-lock.json
- package.json
Relies on ENV variables for AWS credentials setup in the Travis UI
Ensures that updates happen without our intervention.
> Deploy our serverless stack automatically

- .travis.yml
This is what we've been using, production is nice, but too annoying to
change stuff that works already.
> Deploy to the prod stage

- package-lock.json
- package.json
> chore(package): update mocha to version 4.0.1

- package-lock.json
- package.json
> Greenkeeper/node fetch 2.1.1

- package.json
> fix(package): update jsonwebtoken to version 8.1.0

- handler.js
- serverless.yml
This just echoes out the data from the LTI POST. Useful for debugging.
> Add payload function

- package-lock.json
- package.json
> Greenkeeper/eslint 5.0.1

- package-lock.json
- package.json
> Greenkeeper/aws sdk 2.327.0

- bin/lookup.js
Provides a way to find a user Id and validate that parameters work.
> Add lookup command

- package-lock.json
- package.json
We tagged a version without updating these, bring them back into
agreement.
> Align package and release tags

- README.md
- bin/cli.js
- bin/lookup.js
- test/createJWTTest.js
- test/findIliosUserTest.js
- test/readSchoolConfigTest.js
- test/sample-config.json
as an aside - the `config.js` in production should be updated accordingly as well.
> updates api namespace to v2.

- package-lock.json
- package.json
I could be mistaken but it seems to me that serverless is a dev-dependency here used as a deployment tool and not a production dependency to be installed on servers.
> chore: move serverless to dev dependency in package.json

- package-lock.json
Removed package-lock.json and node_modules and did a clean install.
This updates axios from 0.19.2 to 0.21.1.
> chore: update all dependencies

- .eslintrc.yaml
- bin/cli.js
- bin/lookup.js
- handler.js
- lib/createJWT.js
- lib/encodeRFC5987ValueChars.js
- lib/eventToRequest.js
- lib/findIliosUser.js
- lib/launchCourseManager.js
- lib/launchDashboard.js
- lib/ltiRequestValidator.js
- lib/readSchoolConfig.js
- package.json
- test/.eslintrc.yaml
- test/createJWTTest.js
- test/eventToRequestTest.js
- test/findIliosUserTest.js
- test/launchCourseManagerTest.js
- test/launchDashboardTest.js
- test/ltiRequestValidatorTest.js
- test/readSchoolConfigTest.js
This was required by node-fetch and meow and is the future.
> Switch to ESM for modules

- serverless.yml
This is the highest currently supported version.
> Run in Node 14.x on lambda

- package-lock.json
- package.json
> New lock file and engine baseline requirement fix

- .github/workflows/ci.yml
- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-production.yml
- .github/workflows/update-transitive-dependencies.yaml
- package-lock.json
- package.json
- serverless.yml
this isn't the first time i tried to update to v2, see https://github.com/ilios/lti-server/pull/1245
but evidently, it appears we  keep falling back to v1, not quite sure why yet (but suspecting dependabot as the culprit).
> regenerates lockfile using v2.

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-production.yml
When our deploys fail only the author of the last commit gets notified by github actions. Push messages to slack as well.
> Add Deploy Failures Notification

- package.json
- pnpm-lock.yaml
We only install production deps when deploying so we need this here.
> Make Serverless a Production Dependency

- .github/workflows/deploy-dev.yml
Apparently we just pass the directory here
> Fix Path to Package

- package.json
- pnpm-lock.yaml
Not sure if moving this back will fix our error, but let's try it.
> Move @aws-sdk/client-s3 into Dependencies
