serverless.yml
We're going to alias the gateway to lti.iliosproject.org so we don't
need the path to be /lti/dashboard just /dashboard will be fine.
=> Improve the path to our dashboard

.travis.yml
When greenkeeper automatically updates our packages, it needs to update the
lock file as well.
=> Update lockfile when packages get updated

package-lock.json
This is a pre-emptive update to address
https://nvd.nist.gov/vuln/detail/CVE-2018-16487.
=> update lodash to 4.17.11

.travis.yml
NPM is at 6 now, though I think 5 still ships with Node 8. In either
case we don't need to check for this anymore.
=> Remove the installation of NPM 5

lib/findIliosUser.js, package-lock.json, package.json, test/findIliosUserTest.js
Replaces the md5 library with the builtin node crypto and uses the
stronger sha256 algorithm to avoid the possibility of collisions.
Source for the sha256 use: https://stackoverflow.com/a/43232849/796999
=> Hash with sha256

handler.js, lib/encodeRFC5987ValueChars.js, lib/launchResponse.js, lib/ltiRequestValidator.js, package-lock.json, package.json, test/launchResponseTest.js, test/ltiRequestValidatorTest.js
Removes our dependence on https://github.com/omsmith/ims-lti which has been abandoned. Unfortunately there doesn't seem to be a good replacement. Once we've tested this in production it might be worth extracting for general publication.
=> Self validate LTI Request

serverless.yml
This shouldn't be camel cased, we don't use that in URLs anywhere else.
Dasherizing it makes more sense.
=> Fix the course manager path

.travis.yml, package-lock.json, package.json, serverless.yml
Node 8.x is going away soon and lambda is removing this runtime so we
need to bump up. 12.x is the latest stable path so we'll move to it.
=> Upgrade to Node 12.x

.github/workflows/ci.yml, .github/workflows/deploy-dev.yml, .github/workflows/deploy-production.yml, .github/workflows/update-transitive-dependenies.yaml, package.json
Node.js 12 is EOL at the end of April 2022. Update to Node.js 14 which
is the latest version that is supported by AWS.
=> chore: update Node.js to 14.x

.github/workflows/deploy-dev.yml, .github/workflows/deploy-production.yml
This ensures that we don't try and deploy while already deploying.
Any new deployments that are triggered will stack as pending and any
pending deployments will cancel so only the last one runs.
=> Add concurrency limit for deployment runs

.github/workflows/create_release.yaml, .github/workflows/tag_version.yaml
This allows us to easily tag and action with a workflow dispatch event
and respond to newly created tags by adding release notes.
=> Add Workflows to Tag and Release

.github/workflows/automerge.yml
the old version stopped working, see  https://github.com/ilios/lti-server/actions/runs/8110169079/job/22166853719?pr=1655 for an example.
i hope upgrading will set things right again.
=> bump version on automerge action.

.github/dependabot.yml, package-lock.json, package.json
The upgrade of Serverless to v4 requires a license which we haven't obtained yet. Rolling this back for now so we can deploy as we work on that process.
=> Rollback Serverless Upgrade

.github/workflows/deploy-dev.yml, .github/workflows/deploy-production.yml
This should significantly reduce our bundle size, we'll have to test and ensure the application still functions correctly after it is deployed.
=> Skip Installing Dev Dependencies for Deployment

serverless.yml
Attempting to lower our bundle size and this library is included by lambda automatically so we can remove it from our upload and hopefully save a bunch of space.
=> Remove aws-sdk from Deploy

.github/workflows/deploy-dev.yml
Storing this artifact so we can check it out later, then using that created file as the upload. I also found and added a "conceal" option with is probably a good idea in CI as it will hide sensitive stuff in the output.
=> Package and Store the Serverless Deployment

.github/dependabot.yml, .github/workflows/automerge.yml, .github/workflows/update-transitive-dependencies.yaml
I've aligned this with our other less frequently modified apps:
- Dependabot will run weekly and update github actions as well
- Auto merge will happen for any PRs that are minor or patch updates
- Our weekly full lockfile update will automerge
=> Update Dependency Management

.github/workflows/deploy-dev.yml, .github/workflows/deploy-production.yml
We need this same environmental variable for both the package and deploy steps so I moved it up to the top level of the job as it will be available there for all steps.
=> Move SERVERLESS_ACCESS_KEY Up for Deploys

.github/workflows/deploy-dev.yml, .github/workflows/deploy-production.yml
These need to be available in the package step as well apparently, moving them up to the top of the job.
=> Move up AWS env

serverless.yml
Serverless v4 seems to do a better job of packaging out app and I don't think we need this anymore.
=> Remove Package Hack

package.json, pnpm-lock.yaml
This is provided for us by AWS, we don't need it to get deployed.
=> Move aws-sdk to dev dependencies

bin/lookup.js, handler.js, lib/findIliosUser.js, lib/launchCourseManager.js, lib/launchDashboard.js, lib/readSchoolConfig.js, package.json, pnpm-lock.yaml, test/findIliosUserTest.js, test/readSchoolConfigTest.js
I removed the no longer supported SimpleDB service and replace our S3 access code. We'll check performance against the currently deployed code to see how much of a loss the cache is and we can re-implement it with another service if needed.
Fixes #1790
=> Switch out our AWS SDK

.github/workflows/deploy-dev.yml, .github/workflows/deploy-production.yml, package.json, pnpm-lock.yaml
Still trying to find the right combinations here. I've moved serverless and our S3 lib back into dev dependencies where they belong. Let's see if this fixes our issues with data-uri-to-buffer not being in the final payload.
=> Switcharound Dependencies Some More

.github/workflows/deploy-dev.yml, .github/workflows/deploy-production.yml
Lambda doesn't do well with the symlink structure that pnpm creates, instead we need to use this config option on install to create a more traditional node_modules structure.
This issue is specifically documented at https://pnpm.io/next/npmrc#node-linker
and [here](https://github.com/pnpm/pnpm.io/blob/85e23b18c3936d6f0986bc5ed87582e167003403/versioned_docs/version-8.x/npmrc.md?plain=1#L158) is a link to the source for those docs which may be more helpful at some future time.
=> Install Dependencies Correctly for AWS Lambda

.github/workflows/tag_version.yaml
Needed the directory leader otherwise node tries to lookup a global module with this name.
=> Fix Tagging Workflow
